//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odev.Kaynaklar {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("odev.Kaynaklar.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Oturum Aç benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ac {
            get {
                return ResourceManager.GetString("ac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TecnoSozluk, 7 Aralik 2021 tarihinden itibaren yayın hayatına başlamış Türkçe yayın yapan bilişim sitesidir, bilişim teknolojileri alanındaki güncel gelişmeleri kullanıcılar tarafından tartışıldığı web sitesidir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string aciklama {
            get {
                return ResourceManager.GetString("aciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Anasayfa benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string anasafya {
            get {
                return ResourceManager.GetString("anasafya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aralık benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string aralik {
            get {
                return ResourceManager.GetString("aralik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bağlantılar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string baglantilar {
            get {
                return ResourceManager.GetString("baglantilar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cevap Bekleyen Sorular  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string cevap_bekleyen {
            get {
                return ResourceManager.GetString("cevap bekleyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cevaplanmayan Sorular benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string cevaplanmayan {
            get {
                return ResourceManager.GetString("cevaplanmayan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kasım benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string kasim {
            get {
                return ResourceManager.GetString("kasim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Konu Oluştur benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string konu {
            get {
                return ResourceManager.GetString("konu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mart benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string mart {
            get {
                return ResourceManager.GetString("mart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oturum açmak için bir yerel hesap kullanın benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string oturum_ac {
            get {
                return ResourceManager.GetString("oturum ac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   En Son Eklenenler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string son_eklenen {
            get {
                return ResourceManager.GetString("son eklenen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yeni Mesajlar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string yeni {
            get {
                return ResourceManager.GetString("yeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yeni bir hesap oluşturun benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string yeni_hesap {
            get {
                return ResourceManager.GetString("yeni hesap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yönet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string yonet {
            get {
                return ResourceManager.GetString("yonet", resourceCulture);
            }
        }
    }
}
